name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
          validate-wrappers: true
          gradle-home-cache-cleanup: true
          gradle-version: current
      - run: ./gradlew build

  dependency-review:
    runs-on: ubuntu-latest
    needs: dependency-submission
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/dependency-review-action@v4
